const CHANGETHEME = "CHANGETHEME"
const SETUSER = "SETUSER"
const SETUSERPHOTO = "SETUSERPHOTO"
const CALL_NOTIFY = "CALL_NOTIFY"
const CLOSE_NOTIFY = "CLOSE_NOTIFY"
const RESET_NOTIFY = "RESET_NOTIFY"

export {
    CHANGETHEME,
    SETUSER,
    SETUSERPHOTO,
    CALL_NOTIFY,
    CLOSE_NOTIFY,
    RESET_NOTIFY
}